### ISSUE TITLE
Sample Kubernetes deployment

### ISSUE THREAD

**Issue by ngjoh** [koksmat-com/koksmat-documentation#17]
# NATS and Node.js Deployment Guide

This guide outlines the process of deploying NATS, a NATS Box with CLI tools, and a Node.js environment with a sample CLI application in a Kubernetes cluster.

## Overview

The deployment consists of three main components:

1. NATS Server: A single-node NATS server for messaging.
2. NATS Box: A container with NATS and NSC CLI tools for interacting with NATS.
3. Node Box: A Node.js environment that includes a sample CLI application.

## Kubernetes Manifest

Below is the complete Kubernetes manifest that defines all the necessary resources:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name: nats
        image: nats:2.9.15-alpine
        ports:
        - containerPort: 4222
        - containerPort: 8222
        - containerPort: 6222

---
apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  selector:
    app: nats
  ports:
  - name: client
    port: 4222
    targetPort: 4222
  - name: monitoring
    port: 8222
    targetPort: 8222
  - name: cluster
    port: 6222
    targetPort: 6222

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
data:
  .nats.conf: |
    url: nats://nats:4222
    allow_reconnect: true
    max_reconnect_attempts: -1
    reconnect_wait: 2s

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-box
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-box
  template:
    metadata:
      labels:
        app: nats-box
    spec:
      containers:
      - name: nats-box
        image: natsio/nats-box:latest
        command: ["/bin/sh", "-c", "while true; do sleep 30; done;"]
        env:
        - name: NATS_URL
          value: "nats://nats:4222"
        volumeMounts:
        - name: nats-config
          mountPath: /etc/nats
      volumes:
      - name: nats-config
        configMap:
          name: nats-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-box
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-box
  template:
    metadata:
      labels:
        app: node-box
    spec:
      containers:
      - name: node-box
        image: node:18-alpine
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Creating sample CLI..."
          mkdir -p /app
          cat << EOF > /app/cli.js
          #!/usr/bin/env node
          const readline = require('readline');

          const rl = readline.createInterface({
            input: process.stdin,
            output: process.stdout
          });

          function promptUser() {
            rl.question('Enter a command (hello, date, exit): ', (answer) => {
              switch(answer.toLowerCase()) {
                case 'hello':
                  console.log('Hello, World!');
                  break;
                case 'date':
                  console.log(new Date().toLocaleString());
                  break;
                case 'exit':
                  console.log('Goodbye!');
                  rl.close();
                  return;
                default:
                  console.log('Unknown command. Try again.');
              }
              promptUser();
            });
          }

          console.log('Welcome to the sample CLI!');
          promptUser();
          EOF
          chmod +x /app/cli.js
          echo "Sample CLI created. Executing..."
          node /app/cli.js
```

## Deployment Instructions

Follow these steps to deploy the NATS server, NATS Box, and Node.js environment:

1. Save the above YAML to a file named `nats-and-node-deployment.yaml`.

2. Apply the manifest using kubectl:
   ```bash
   kubectl apply -f nats-and-node-deployment.yaml
   ```

3. Wait for all pods to be in the "Running" state:
   ```bash
   kubectl get pods -w
   ```

### Interacting with NATS Box

To use the NATS and NSC CLI tools:

1. Execute an interactive shell in the NATS Box:
   ```bash
   kubectl exec -it deployment/nats-box -- /bin/sh
   ```

2. Once inside the NATS Box, you can use `nats` and `nsc` commands. For example:
   ```bash
   # Test NATS connection
   nats ping

   # Use NSC to create an operator
   nsc add operator --name MyOperator

   # Add an account
   nsc add account --name MyAccount

   # Add a user
   nsc add user --name MyUser --account MyAccount
   ```

### Using the Node.js Sample CLI

To interact with the Node.js sample CLI:

1. Execute an interactive shell in the Node Box:
   ```bash
   kubectl exec -it deployment/node-box -- /bin/sh
   ```

2. Once inside the Node Box, run the sample CLI:
   ```bash
   node /app/cli.js
   ```

3. You can now interact with the CLI by entering commands like "hello", "date", or "exit".

## Customization

You can customize this setup by:

1. Modifying the NATS server configuration for production use.
2. Expanding the sample CLI in the Node Box to include more complex functionality.
3. Adding persistent storage for NATS or the Node.js environment.
4. Implementing proper authentication and authorization for NATS.
5. Setting up monitoring and alerting for your NATS cluster.

Remember to adjust resource limits, implement security measures, and follow best practices when adapting this setup for production use.
